BaseURL= "https://sayanchowdhury.dgplug.org/"
LanguageCode= "en-us"
Title= "Intellectual Web"
paginate = 5
DisqusShortname = "sayanchowdhury"
Copyright = "All rights reserved - 2016"
canonifyurls = true
theme="beautifulhugo"

[params]
  cover = "images/cover.jpg"
  googleAnalytics = "UA-41061985-1"
  logo = "images/yoda.jpg"
  hideHUGOSupport = false

[author]
  name = "Sayan Chowdhury"
  github = "sayanchowdhury"
  twitter = "yudocaa"
  facebook = "synpro"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Blog"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "Github"
  weight = 100
  url = "https://github.com/sayanchowdhury"

[[menu.main]]
  name = "Twitter"
  weight = 101
  url = "https://twitter.com/yudocaa"
