BaseUrl= "http://sayanchowdhury.dgplug.org/"
LanguageCode= "en-us"
Title= "Intellectual Web"
paginate = 5
DisqusShortname = "sayanchowdhury"
Copyright = "All rights reserved - 2015"
canonifyurls = true
theme="casper"

[params]
  cover = "images/cover.jpg"
  author = "Sayan Chowdhury"
  authorlocation = "Bangalore, India"
  authorwebsite = "http://sayanchowdhury.dgplug.org"
  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  githubName = "sayanchowdhury"
  twitterName = "chowdhury_sayan"
  # facebookName = "synpro"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Blog"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "Github repos"
  weight = 100
  url = "https://github.com/sayanchowdhury"

[[menu.main]]
  name = "Twitter timeline"
  weight = 101
  url = "https://twitter.com/chowdhury_sayan"
